### ISSUE TITLE
This line is causing errors 

### ISSUE THREAD

**Issue by CassandraCerasia** [jpuritz/BIO_594#3]
https://github.com/jpuritz/BIO_594/blame/6bff61f7adfe9c7accad09122647904f9fb9e930/Final_Project/Collaborative_Final_Project_Part_2_ReferenceAssembly_Cass.Rmd#L261

Whenever I run this line of code (bash remake_reference.sh 4 4 0.90 PE 2) I keep getting an error which states  "sort: write failed: standard output: Broken pipe
sort: write error." Does anyone know how I can get past this? I am going to try to just let it run overnight since the errors do not stop the code but it has been a few hours and it is still running so I am not so hopeful. Once I get beyond this issue, I believe I can finish my assigned part in about 30-45 minutes at the absolute most, so it shouldn't be much of a delay but I apologize for any inconvenience!

**Comment by jpuritz** [comment]
Try running it outside of RStudio (normal terminal). Also, this code is
the same as running dDocent (but saying “no” to read trimming, mapping, and
SNP calling).

Jon Puritz, PhD (he/him)

Associate Professor
Department of Biological Sciences
University of Rhode Island
120 Flagg Road, Kingston, RI 02881


Webpage: MarineEvoEco.com

Cell:    401-338-8739
Work:  401-874-9020

"The most valuable of all talents is that of never using two words when one
will do.” -Thomas Jefferson
--------------------------------------------
*The University of Rhode Island occupies the traditional stomping ground of
the Narragansett Nation and the Niantic People. *
