### ISSUE TITLE
Output is not working for RefMapOpt.sh 4 8 4 8 0.9 64 PE

### ISSUE THREAD

**Issue by CassandraCerasia** [jpuritz/BIO_594#5]
https://github.com/jpuritz/BIO_594/blame/f9767c3725e898b4482e0652e605854d0b997161/Final_Project/Collaborative_Final_Project_Part_2_ReferenceAssembly_Cass.Rmd#L66

I am having issues with RefMapOpt.sh 4 8 4 8 0.9 64 PE. When I run it, it says

"Usage is RefMapOpt minK1 maxK1 minK2 maxK2 cluster_similarity Assembly_Type Num_of_Processors optional_list_of_individuals
Please make sure to choose assembly type."

However, I thought the assembly type was PE, which is in the code. But in the usage, it says that assembly type comes before the number of processors. Is the number of processors 64, and should PE and 64 be switched around? 64 processors seems like an awful lot. My idea is: RefMapOpt.sh 4 8 4 8 0.9 PE 64, but that seems like an awful lot of processors.

**Comment by jpuritz** [comment]
Follow the usage.  64 is fine for now.
